# 1. Crear un DataFrame usando Arrays

In [40]:
import numpy as np
import pandas as pd

In [49]:
# Creando Array
array = np.array([[1,2],[3,4],[5,6],[7,8],[9,19]])

In [52]:
# Creando DataFrame
pd.DataFrame(array)

   0   1
0  1   2
1  3   4
2  5   6
3  7   8
4  9  19

# 2. Crear un DataFrame usando Diccionarios

In [54]:
states = ["California","Texas","Arizona","Florida"]
population = [75432,13456,98765,43212]

In [57]:
dictionary = {"States":states, "Population":population}

In [59]:
pd.DataFrame(dictionary)

       States  Population
0  California       75432
1       Texas       13456
2     Arizona       98765
3     Florida       43212

# 3. Creando Dataframe usando .CSV

In [118]:
mining_warehouse = pd.read_csv(
    r'C:\Users\Mateo Alvarez\OneDrive\Documentos\DATASET_FACTORY\output\Movimientos_Almacen\mining_warehouse_movements.csv',
    sep=';',
)
mining_warehouse

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
0,MOV-0000001,2/10/2023,2023,10,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00004-0000,NaN,...,13.80,427.80,143,112,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
1,MOV-0000002,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00009-0000,MIN-001,...,123.20,985.60,17,9,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
2,MOV-0000003,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00020-0000,MIN-002,...,879.44,1758.88,2,0,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
3,MOV-0000004,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00025-0000,MIN-004,...,101.84,611.04,13,7,Logística Interna,NaN,NaN,NaN,NaN,Analista de Inventario
4,MOV-0000005,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00026-0000,MIN-007,...,97.91,195.82,3,1,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129088,MOV-0129089,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00509-0154,MIN-004,...,22.98,22.98,1,0,Perforación y Voladura,NaN,NaN,NaN,NaN,Almacenero
129089,MOV-0129090,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00514-0154,MIN-002,...,42.30,42.30,2,1,Perforación y Voladura,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
129090,MOV-0129091,14/9/2026,2026,9,Lunes,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00515-0153,MIN-005,...,7.80,335.40,27,70,NaN,NaN,NaN,14/9/2026,NaN,Jefe de Abastecimiento
129091,MOV-0129092,14/9/2026,2026,9,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00518-0154,NaN,...,45.69,1370.70,79,49,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
129092,MOV-0129093,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00519-0154,MIN-005,...,4.88,48.80,21,11,Mantenimiento Mina,NaN,NaN,NaN,NaN,Supervisor de Almacén